version: '3.8'

services:
    nginx:
        build:
            context: api/docker/dev
            dockerfile: nginx/Dockerfile
        depends_on:
            - api-fpm
            - api-cli
        container_name: demo_bank_nginx
        ports:
            - 80:80
        volumes:
            - ./api:/var/www/demo_bank
    api-fpm:
        build:
            context: api/docker/dev
            dockerfile: php-fpm/Dockerfile
        container_name: demo_bank_fpm
        volumes:
            - ./api:/var/www/demo_bank
    api-cli:
        build:
            context: api/docker/dev
            dockerfile: php-cli/Dockerfile
        container_name: demo_bank_cli
        volumes:
            - ./api:/var/www/demo_bank
