version: '3.8'

services:
    nginx:
        build:
            context: api/docker/dev
            dockerfile: nginx/Dockerfile
        depends_on:
            - api-fpm
            - api-cli
        container_name: demo_bank1_nginx
        ports:
            - 80:80
        volumes:
            - ./api:/var/www/demo_bank1
    api-fpm:
        build:
            context: ./
            dockerfile: api/docker/dev/php-fpm/Dockerfile
        container_name: demo_bank1_fpm
        volumes:
            - ./api:/var/www/demo_bank1
        depends_on:
            - maria-db
    api-cli:
        build:
            context: ./
            dockerfile: api/docker/dev/php-cli/Dockerfile
        container_name: demo_bank1_cli
        volumes:
            - ./api:/var/www/demo_bank1
        tty: true
        stdin_open: true
        depends_on:
            - maria-db
    maria-db:
        image: mariadb:10.4.17-focal
        restart: always
        volumes:
            - ./api/docker/mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        container_name: ${DB_HOST}