#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use DI\ContainerBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

$application = new Application();
$containerBuilder = new ContainerBuilder();

$dependencies = require __DIR__ . '/app/dependencies.php';
$settings = require __DIR__ . '/app/settings.php';
// Set up settings
$settings($containerBuilder);
// Set up dependencies
$dependencies($containerBuilder);
$container = $containerBuilder->build();


$commands = $container->get('commands');
$entityManager = $container->get(EntityManagerInterface::class);
$application->getHelperSet()
    ->set(new EntityManagerHelper($entityManager), 'em');
//
foreach ($commands as $name) {
    /** @var Command $command */
    $command = $container->get($name);
    $application->add($command);
}

$application->run();